name: Lint
on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '22'
          cache: npm
      - run: npm ci
      - run: npm run build
      - run: npm run lint
